hpc_determining_command: squeue # If this command is found, treat machine as HPC
hpc_submit_command: sbatch

# Determine job run time and resources
hpcs:
  getafix:
    account: smp
    conda_env: Barry
    job_script_name: getafix
    num_fits_per_job: 1
    mpi_module: rocks-openmpi
    fort_compile_module: intel/2018.1.163

  nersc:
    account: desi
    conda_env: cosmopipe
    job_script_name: nersc
    num_fits_per_job: 32
    mpi_module: openmpi
    fort_compile_module: intel

